# cloudlab.conf
# This file is used to configure the cloudlab environment 

# Cloulab config:
# ------------------------------------------
DOMAIN=apt.emulab.net
# DOMAIN=clemson.cloudlab.us
# DOMAIN=utah.cloudlab.us
# DOMAIN=wisc.cloudlab.us
# MACHINES=( "hp177" "hp052" "hp171" "hp163" "hp186" "hp199" "hp196" "hp172" "hp067" "hp188" )
MACHINES=(
  "apt181"
  "apt177"
  "apt175"
  "apt185"
  "apt180"
  "apt150"
  "apt146"
  "apt157"
  "apt141"
  "apt173"
)
USER=alclev
# ------------------------------------------
