# cloudlab.conf
# This file is used to configure the cloudlab environment 

# Cloulab config:
# ------------------------------------------
DOMAIN=apt.emulab.net
# DOMAIN=clemson.cloudlab.us
# DOMAIN=utah.cloudlab.us
# DOMAIN=wisc.cloudlab.us
MACHINES=( "apt072" "apt106" "apt139" "apt081" "apt123" "apt113" "apt150" "apt083" "apt138" "apt161" )
USER=alclev
# ------------------------------------------
