# cloudlab.conf
# This file is used to configure the cloudlab environment 

# Cloulab config:
# ------------------------------------------
DOMAIN=apt.emulab.net
# DOMAIN=clemson.cloudlab.us
# DOMAIN=utah.cloudlab.us
# DOMAIN=wisc.cloudlab.us
# MACHINES=( "hp177" "hp052" "hp171" "hp163" "hp186" "hp199" "hp196" "hp172" "hp067" "hp188" )
MACHINES=( "apt183" "apt186" "apt181" "apt173" "apt182" "apt177" "apt174" "apt180" "apt179" "apt192" )
USER=alclev
# ------------------------------------------
